### ISSUE TITLE
 HDF5-DIAG can not read data

### ISSUE THREAD

**Issue by huanqingxu** [koncle/CoraNet#2]
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5F.c line 370 in itk_H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 830 in itk_H5F__is_hdf5(): unable to locate file signature
    major: File accessibilty
    minor: Not an HDF5 file
  #002: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 126 in itk_H5FD_locate_signature(): unable to read file signature
    major: Low-level I/O
    minor: Unable to initialize object
  #003: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 205 in itk_H5FD_read(): driver read request failed
    major: Virtual File Layer
    minor: Read failed
  #004: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDsec2.c line 725 in H5FD_sec2_read(): file read failed: time = Fri Nov 26 10:42:53 2021
, filename = '/media/lab549/CE56C94660FE3E83/semantic_segmentation_xhq/code_xhq/CoraNet-master/dataset/Pancreas-CT/data/Pancreas-CT/PANCREAS_0001/11-24-2015-PANCREAS0001-Pancreas-18957/Pancreas-99667', file descriptor = 4, errno = 21, error message = 'Is a directory', buf = 0x7fff8af532a8, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0
    major: Low-level I/O
    minor: Read failed
Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:

**Comment by koncle** [comment]
It seems that your data structure `CoraNet-master/dataset/Pancreas-CT/data/Pancreas-CT/` is wrong. It should be :
```
pancreas
├── Pancreas-CT
└── Pancreas-CT-Label
```
Then you can process the data with `preprocess/pancreas_preprocess.py` by setting  data_root to `prancreas` and the variable `path`  in  `generate_h5_data` method to `Pancreas-CT`.

I have updated  `README.md` and `preprocess/pancreas_preprocess.py` for an easier processing.

**Comment by huanqingxu** [comment]
thank you very much.i have solved it.all the best.



---Original---
From: ***@***.***&gt;
Date: Thu, Dec 2, 2021 16:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [koncle/CoraNet]  HDF5-DIAG can not read data (Issue #2)




 
It seems that your data structure CoraNet-master/dataset/Pancreas-CT/data/Pancreas-CT/ is wrong. It should be :
 pancreas ├── Pancreas-CT └── Pancreas-CT-Label  
Then you can process the data with preprocess/pancreas_preprocess.py by setting the data_root to prancreas and the variable path to Pancreas-CT in  generate_h5_data method.
 
I have updated the README.md and preprocess/pancreas_preprocess.py for an easier processing.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
